### ISSUE TITLE
Internal Server Error when trying to open app details

### ISSUE THREAD

**Issue by PedroPini** [palfrey/wharf#87] opened 2020-06-02 04:33 UTC
First I would like to say thank's for the great work.
The error that I am facing is related with the postgres, firstly I had change my postgres plugin version to postgres:12, so I saw an issue that it says that the  Postgres plugin version should be  >1.9.5. So I've created another dockerfile with the same postgres image being used on the plugin, which is 11.6 and still so I am facing the same error, would you have any guess?

![image](https://user-images.githubusercontent.com/20143363/83480006-c2ff0d00-a4cc-11ea-901c-8aeb889c68e3.png)

**Comment by palfrey** [comment] 2020-06-02 09:40
The README says "versions up to 1.9.5". That your log contains the text "Postgres services" indicates you're using a version of dokku-postgres that's a version after 1.9.5.

Closing as duplicate of #75

**Closed by palfrey** 2020-06-02 09:40 UTC
