### ISSUE TITLE
Cant deploy Wharf

### ISSUE THREAD

**Issue by robertorubioguardia** [palfrey/wharf#58] opened 2019-07-25 10:50 UTC
Hi there,

I keep getting this while deploying Wharf in a newly installed Dokku instance. Same process we have done before with no issues:

 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@paas.servidoresrapidos.net:wharf'

Any hints please?

Cheers.

**Comment by robertorubioguardia** [comment] 2019-07-25 11:07
I am also geting:

No Procfile found in app image

and:
 
remote: App container failed to start!!

There are previous commits that are supposed to fix this but using the latest version of the repo is not working :(

**Comment by R-2-D-2** [comment] 2019-07-25 13:43
Hi there,
I'm facing the same issue and couldn't fix it yet. I'm with a fresh Ubuntu 18.04 installation and checked out the solved issues #22 and #34 . 

Will dig now through the debug output...

Cheers

**Comment by R-2-D-2** [comment] 2019-07-25 14:14
Hi Roberto,
I could get rid of the issue, disabling the checks on the Dokku host for the wharf app:
`dokku checks:disable wharf`

Afterwards I can push the repo. I do not get a VHost assigned yet, but as I'm just starting with Dokku, this issue might be my knowledge ;-) 

Cheers

**Comment by palfrey** [comment] 2019-07-26 10:43
So I'm not able to reproduce this, either locally or in a new build of the test suite (https://travis-ci.com/palfrey/wharf/builds/120838360). If you can try running that and write patches for it that reproduce your problem, or write out a very specific set of steps you're doing so I can try and reproduce this I might be able to make fixes, but right now I can't reproduce any of this.

**Comment by ammoniak** [comment] 2019-10-17 12:08
I have the same issue. Fresh install with an ubuntu (the latest one with LTS)

**Comment by palfrey** [comment] 2019-10-17 12:35
@ammoniak What's the exact set of steps you did with the install?

**Comment by ammoniak** [comment] 2019-10-17 12:40
First I installed Ubuntu. Updateded everything (apt upgrade).
Then I installed python and generated ssh-keys for my user and for root.
Then I followed these steps (from the readme):
1. Install Dokku
2. Install the following plugins:
https://github.com/dokku/dokku-redis
https://github.com/dokku/dokku-postgres
https://github.com/dokku/dokku-letsencrypt
3. Setup the Let's Encrypt plugin to auto-renew (dokku letsencrypt:cron-job --add)
4. Create the app (dokku apps:create wharf)
5. Add SSH key storage:
mkdir /var/lib/dokku/data/storage/wharf-ssh/
chown dokku:dokku /var/lib/dokku/data/storage/wharf-ssh/
dokku storage:mount wharf /var/lib/dokku/data/storage/wharf-ssh/:/root/.ssh
6. Add Redis (dokku redis:create wharf && dokku redis:link wharf wharf)
7. Add Postgres (dokku postgres:create wharf && dokku postgres:link wharf wharf)
Set ADMIN_PASSWORD to something secret (dokku config:set wharf ADMIN_PASSWORD=somesecret)
8. Deploy this Git repo as per the standard Dokku instructions

Everything works up untill I try to push to dokku (git push dokku master)

**Comment by palfrey** [comment] 2019-10-17 12:42
Thanks. I'll have a look at that tonight...

**Comment by ammoniak** [comment] 2019-10-17 12:55
This is the output I get:
`  creating build/temp.linux-x86_64-3.8/psycopg                                                                                                                                          gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DPSYCOPG_DEFAULT_PYDATETIME=1 -DPSYCOPG_VERSION=2.7.5 (dt dec pq3 ext lo64) -DPG_VERSION_NUM=110005 -DHAVE_LO64=1 -I/usr/local/include/python3.8 -I. -I/usr/include/postgresql -I/usr/include/postgresql/11/server -c psycopg/psycopgmodule.c -o build/temp.linux-x86_64-3.8/psycopg/psycopgmodule.o -Wdeclaration-after-statement                                                                                                                                            psycopg/psycopgmodule.c: In function ‘psyco_is_main_interp’:                                                                                                                          psycopg/psycopgmodule.c:689:18: error: dereferencing pointer to incomplete type ‘PyInterpreterState’ {aka ‘struct _is’}                                                                    while (interp->next)                                                                                                                                                                               ^~                                                                                                                                                                                                                                                                                                                                                        It appears you are missing some prerequisite to build the package from source.                                                                                                                                                                                                                                                                                              You may install a binary package by installing 'psycopg2-binary' from PyPI.                                                                                                           If you want to install psycopg2 from source, please install the packages                                                                                                              required for the build and try again.                                                                                                                                                                                                                                                                                                                                       For further information please check the 'doc/src/install.rst' file (also at                                                                                                          <http://initd.org/psycopg/docs/install.html>).                                                                                                                                                                                                                                                                                                                              error: command 'gcc' failed with exit status 1                                                                                                                                        ----------------------------------------                                                                                                                                              ERROR: Failed building wheel for psycopg2-binary                                                                                                                                      Running setup.py clean for psycopg2-binary                                                                                                                                            Building wheel for pycparser (setup.py): started                                                                                                                                      Building wheel for pycparser (setup.py): finished with status 'done'                                                                                                                  Created wheel for pycparser: filename=pycparser-2.18-py2.py3-none-any.whl size=205601 sha256=f1ec3fe9b29b5703d28570dba06355b8e647b1028721f2e01afcb209770ec60b                         Stored in directory: /root/.cache/pip/wheels/c0/a1/27/5ba234bd77ea5a290cbf6d675259ec52293193467a12ef1f46                                                                              Building wheel for timeout-decorator (setup.py): started                                                                                                                              Building wheel for timeout-decorator (setup.py): finished with status 'done'                                                                                                          Created wheel for timeout-decorator: filename=timeout_decorator-0.4.1-cp38-none-any.whl size=5021 sha256=c12e316b2b4622356a55a222a9209fa72a9f9c01a351c9e55d5803f4da6b82d9             Stored in directory: /root/.cache/pip/wheels/f1/e6/ea/7387e3629cb46ba65140141f972745b823f4486c6fe884ccb8                                                                            Successfully built humanize markupsafe pycparser timeout-decorator                                                                                                                    Failed to build cffi psycopg2-binary                                                                                                                                                  Installing collected packages: vine, amqp, asn1crypto, pycparser, cffi, six, bcrypt, billiard, pytz, kombu, redis, celery, certifi, chardet, idna, cryptography, dj-database-url, django-celery-results, markupsafe, jinja2, django, django-jinja, django-jinja-bootstrap-form, django-redis, smmap2, gitdb2, gitpython, humanize, pyasn1, pynacl, paramiko, psycopg2-binary, urllib3, requests, selenium, timeout-decorator                                                                                                                                          Running setup.py install for cffi: started                                                                                                                                            Running setup.py install for cffi: finished with status 'error'                                                                                                                       ERROR: Command errored out with exit status 1:                                                                                                                                         command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-t5mhe4ub/cffi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-t5mhe4ub/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-9kija4oo/install-record.txt --single-version-externally-managed --compile                                                                                       cwd: /tmp/pip-install-t5mhe4ub/cffi/                                                                                                                                             Complete output (41 lines):                                                                                                                                                           running install                                                                                                                                                                       running build                                                                                                                                                                         running build_py                                                                                                                                                                      creating build                                                                                                                                                                        creating build/lib.linux-x86_64-3.8                                                                                                                                                   creating build/lib.linux-x86_64-3.8/cffi                                                                                                                                              copying cffi/verifier.py -> build/lib.linux-x86_64-3.8/cffi                                                                                                                           copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-3.8/cffi                                                                                                                        copying cffi/cparser.py -> build/lib.linux-x86_64-3.8/cffi                                                                                                                            copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-3.8/cffi                                                                                                                     copying cffi/recompiler.py -> build/lib.linux-x86_64-3.8/cffi                                                                                                                         copying cffi/__init__.py -> build/lib.linux-x86_64-3.8/cffi                                                                                                                           copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-3.8/cffi                                                                                                                     copying cffi/ffiplatform.py -> build/lib.linux-x86_64-3.8/cffi                                                                                                                        copying cffi/api.py -> build/lib.linux-x86_64-3.8/cffi                                                                                                                                copying cffi/error.py -> build/lib.linux-x86_64-3.8/cffi                                                                                                                              copying cffi/model.py -> build/lib.linux-x86_64-3.8/cffi                                                                                                                              copying cffi/vengine_gen.py -> build/lib.linux-x86_64-3.8/cffi                                                                                                                        copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-3.8/cffi                                                                                                                        copying cffi/lock.py -> build/lib.linux-x86_64-3.8/cffi                                                                                                                               copying cffi/commontypes.py -> build/lib.linux-x86_64-3.8/cffi                                                                                                                        copying cffi/_cffi_include.h -> build/lib.linux-x86_64-3.8/cffi                                                                                                                       copying cffi/parse_c_type.h -> build/lib.linux-x86_64-3.8/cffi                                                                                                                        copying cffi/_embedding.h -> build/lib.linux-x86_64-3.8/cffi                                                                                                                          copying cffi/_cffi_errors.h -> build/lib.linux-x86_64-3.8/cffi                                                                                                                        running build_ext                                                                                                                                                                     building '_cffi_backend' extension                                                                                                                                                    creating build/temp.linux-x86_64-3.8                                                                                                                                                  creating build/temp.linux-x86_64-3.8/c                                                                                                                                                gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/local/include/python3.8 -c c/_cffi_backend.c -o build/temp.linux-x86_64-3.8/c/_cffi_backend.o                                                                                                                                               c/_cffi_backend.c: In function ‘b_do_dlopen’:                                                                                                                                         c/_cffi_backend.c:4197:31: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]                                                                    *p_printable_filename = PyText_AsUTF8(s);                                                                                                                                                                   ^                                                                                                                                                      In file included from c/cffi1_module.c:20,                                                                                                                                                             from c/_cffi_backend.c:7370:                                                                                                                                         c/call_python.c: In function ‘_get_interpstate_dict’:                                                                                                                                 c/call_python.c:20:30: error: dereferencing pointer to incomplete type ‘PyInterpreterState’ {aka ‘struct _is’}                                                                             builtins = tstate->interp->builtins;                                                                                                                                                                           ^~                                                                                                                                                      error: command 'gcc' failed with exit status 1                                                                                                                                        ----------------------------------------                                                                                                                                          ERROR: Command errored out with exit status 1: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-t5mhe4ub/cffi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-t5mhe4ub/cffi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-9kija4oo/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.     remote: The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1                                                                                          remote:                                                                                                                                                                               To localhost:wharf                                                                                                                                                                     ! [remote rejected] master -> master (pre-receive hook declined)                                                                                                                     error: failed to push some refs to 'dokku@localhost:wharf'                `

**Comment by palfrey** [comment] 2019-10-17 13:35
Ah-hah! Thanks for that. I've just been able to reproduce this with `docker build .`. I'll investigate and add that step to the build tests.

**Comment by palfrey** [comment] 2019-10-17 18:40
I just merged #63 which certainly fixes the version of this I was able to reproduce. If you can retest with that, that would be very useful!

**Comment by ammoniak** [comment] 2019-10-17 18:50
That fixed it for me. Thank you. Let me know if I can help you with something else.

**Comment by palfrey** [comment] 2019-10-18 10:04
Awesome, thanks. I'm closing this issue now, but if anyone else still has issues, please comment

**Closed by palfrey** 2019-10-18 10:04 UTC
